name = "server"
main = "src/index.ts"
compatibility_date = "2024-10-09"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true
route=""

[vars]
SUPABASE_URL = "your_supabase_url_here"
SUPABASE_ANON_KEY = "your_supabase_anon_key_here"